<a href="https://colab.research.google.com/github/14marcos1/pesquisa_quimica_2026/blob/main/quimica001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# PASSO 1 — carregar a planilha sigilosa no Colab e inspecionar a estrutura
!pip -q install pandas openpyxl scikit-learn matplotlib seaborn

import pandas as pd

arquivo = "/content/Tabela analise multivariada_FJMN (2).xlsx"  # ajuste se necessário

# ver abas
xls = pd.ExcelFile(arquivo)
print("Abas:", xls.sheet_names)

# ler a primeira aba
df = pd.read_excel(arquivo, sheet_name=0)
print(df.shape)
display(df.head())
print(df.columns.tolist())

Abas: ['Abreviações', 'Componentes dos óleos', 'Cicatrização (área da ferida)', 'Cicatr.(contração da ferida)', 'Fotoproteção (ABSORÇÃO)', 'Fotoproteção (FPS)', 'Antibacteriana', 'Estresse oxid.(FRAP)', 'Estres. Oxid.(MDA)', 'Estr. Oxid.(Proteinas)', 'Estr. Oxd.(SOD)', 'Estr. Oxid. (Catalase)']
(14, 2)

   Código            Tipo de óleo/ tratamento
0     NaN                                 NaN
1  GC(-)S  Controle negativo (salina, 1% m/v)
2  GC(+)D        Controle positivo (Dersani®)
3     OCC             Óleo de grão cru cereja
4     OCB               Óleo de grão cru boia

['Código', 'Tipo de óleo/ tratamento']

In [3]:
import pandas as pd

arquivo = "/content/Tabela analise multivariada_FJMN (2).xlsx"

# ver abas
xls = pd.ExcelFile(arquivo)
print(xls.sheet_names)

# 1) componentes químicos
df_x = pd.read_excel(arquivo, sheet_name="Componentes dos óleos")
print("X:", df_x.shape)
display(df_x.head())
print(df_x.columns.tolist())

# 2) escolher UM desfecho biológico, por exemplo:
df_y = pd.read_excel(arquivo, sheet_name="Cicatrização (área da ferida)")
print("Y:", df_y.shape)
display(df_y.head())
print(df_y.columns.tolist())

['Abreviações', 'Componentes dos óleos', 'Cicatrização (área da ferida)', 'Cicatr.(contração da ferida)', 'Fotoproteção (ABSORÇÃO)', 'Fotoproteção (FPS)', 'Antibacteriana', 'Estresse oxid.(FRAP)', 'Estres. Oxid.(MDA)', 'Estr. Oxid.(Proteinas)', 'Estr. Oxd.(SOD)', 'Estr. Oxid. (Catalase)']
X: (38, 16)

,Unnamed: 0,Composto,Teor (mg/mL),Unnamed: 3,Unnamed: 4,Teor (mg/mL).1,Unnamed: 6,Unnamed: 7,Teor (mg/mL).2,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Teor (mg/mL).3,Unnamed: 15
0,tR (min),NaN,OCV,OCV-B,NaN,OCB,OCB-B,NaN,OCC,OCC-TC,OCC-TM,OCC-TE,OCC-TME,NaN,OC-BR,OC-BD
1,5.71,Ácido palmítico,1.811095,4.755756,NaN,1.939807,3.088236,NaN,0.504649,0.782495,1.895978,2.408786,3.676306,NaN,0.885206,0.711454
2,6.39,Cafeína,0.370544,1.009628,NaN,0.349252,0.564784,NaN,0.314963,0.360212,0.631691,0.553139,0.54365,NaN,0.359316,0.215336
3,6.47,Ácido linoleico,1.010604,1.706466,NaN,0.989264,1.003551,NaN,0.444661,0.85243,1.381854,1.249773,1.20735,NaN,1.584211,0.74008
4,8.13,Caveal,0.550683,0.513038,NaN,0.634226,0.560683,NaN,1.00562,1.209463,2.07564,2.008629,2.062697,NaN,0.555683,0.634226

['Unnamed: 0', 'Composto', 'Teor (mg/mL)', 'Unnamed: 3', 'Unnamed: 4', 'Teor (mg/mL).1', 'Unnamed: 6', 'Unnamed: 7', 'Teor (mg/mL).2', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Teor (mg/mL).3', 'Unnamed: 15']
Y: (152, 21)

,Tratamento,Dia zero,Dia 4,Dia 8,Unnamed: 4,Unnamed: 5,Unnamed: 6,DIA ZERO,Unnamed: 8,Dia 4.1,...,Dia 8.1,Unnamed: 12,Unnamed: 13,DIA ZERO.1,Unnamed: 15,Unnamed: 16,Dia 4.2,Unnamed: 18,Dia 8.2,Unnamed: 20
0,NaN,Área (Média),Área (Média),Área (Média),NaN,NaN,Tratamento,Grupo,Area (mm2),GRUPO,...,GRUPO,Area (mm2),NaN,Tratamento,Grupo,área (mm2),Grupo,área (mm2),Grupo,área (mm2)
1,NaN,NaN,NaN,NaN,NaN,NaN,GD(+),C1,77.716,C1,...,NaN,NaN,NaN,OCC-TC,C1,67.335,C1,42.558,NaN,NaN
2,GD(+),82.019909,60.982333,36.4602,NaN,NaN,GD(+),C2,80.611,NaN,...,C2,33.558,NaN,OCC-TC,C2,137.562,NaN,NaN,C2,29.708
3,GS(-),70.579875,99.9,38.42,NaN,NaN,GD(+),C3,91.001,NaN,...,C3,59.947,NaN,OCC-TC,C3,94.324,NaN,NaN,C3,19.772
4,OCV,60.35675,57.88975,29.83225,NaN,NaN,GD(+),C4,98.15,C4,...,NaN,NaN,NaN,OCC-TC,C4,104.873,NaN,NaN,C4,37.599

['Tratamento', 'Dia zero', 'Dia 4', 'Dia 8', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'DIA ZERO', 'Unnamed: 8', 'Dia 4.1', 'Unnamed: 10', 'Dia 8.1', 'Unnamed: 12', 'Unnamed: 13', 'DIA ZERO.1', 'Unnamed: 15', 'Unnamed: 16', 'Dia 4.2', 'Unnamed: 18', 'Dia 8.2', 'Unnamed: 20']

In [4]:
import pandas as pd

arquivo = "/content/Tabela analise multivariada_FJMN (2).xlsx"

# ver abas
xls = pd.ExcelFile(arquivo)
print(xls.sheet_names)

# 1) componentes químicos
df_x = pd.read_excel(arquivo, sheet_name="Componentes dos óleos")
print("X:", df_x.shape)
display(df_x.head())
print(df_x.columns.tolist())

# 2) escolher UM desfecho biológico, por exemplo:
df_y = pd.read_excel(arquivo, sheet_name="Cicatrização (área da ferida)")
print("Y:", df_y.shape)
display(df_y.head())
print(df_y.columns.tolist())

['Abreviações', 'Componentes dos óleos', 'Cicatrização (área da ferida)', 'Cicatr.(contração da ferida)', 'Fotoproteção (ABSORÇÃO)', 'Fotoproteção (FPS)', 'Antibacteriana', 'Estresse oxid.(FRAP)', 'Estres. Oxid.(MDA)', 'Estr. Oxid.(Proteinas)', 'Estr. Oxd.(SOD)', 'Estr. Oxid. (Catalase)']
X: (38, 16)

,Unnamed: 0,Composto,Teor (mg/mL),Unnamed: 3,Unnamed: 4,Teor (mg/mL).1,Unnamed: 6,Unnamed: 7,Teor (mg/mL).2,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Teor (mg/mL).3,Unnamed: 15
0,tR (min),NaN,OCV,OCV-B,NaN,OCB,OCB-B,NaN,OCC,OCC-TC,OCC-TM,OCC-TE,OCC-TME,NaN,OC-BR,OC-BD
1,5.71,Ácido palmítico,1.811095,4.755756,NaN,1.939807,3.088236,NaN,0.504649,0.782495,1.895978,2.408786,3.676306,NaN,0.885206,0.711454
2,6.39,Cafeína,0.370544,1.009628,NaN,0.349252,0.564784,NaN,0.314963,0.360212,0.631691,0.553139,0.54365,NaN,0.359316,0.215336
3,6.47,Ácido linoleico,1.010604,1.706466,NaN,0.989264,1.003551,NaN,0.444661,0.85243,1.381854,1.249773,1.20735,NaN,1.584211,0.74008
4,8.13,Caveal,0.550683,0.513038,NaN,0.634226,0.560683,NaN,1.00562,1.209463,2.07564,2.008629,2.062697,NaN,0.555683,0.634226

['Unnamed: 0', 'Composto', 'Teor (mg/mL)', 'Unnamed: 3', 'Unnamed: 4', 'Teor (mg/mL).1', 'Unnamed: 6', 'Unnamed: 7', 'Teor (mg/mL).2', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Teor (mg/mL).3', 'Unnamed: 15']
Y: (152, 21)

,Tratamento,Dia zero,Dia 4,Dia 8,Unnamed: 4,Unnamed: 5,Unnamed: 6,DIA ZERO,Unnamed: 8,Dia 4.1,...,Dia 8.1,Unnamed: 12,Unnamed: 13,DIA ZERO.1,Unnamed: 15,Unnamed: 16,Dia 4.2,Unnamed: 18,Dia 8.2,Unnamed: 20
0,NaN,Área (Média),Área (Média),Área (Média),NaN,NaN,Tratamento,Grupo,Area (mm2),GRUPO,...,GRUPO,Area (mm2),NaN,Tratamento,Grupo,área (mm2),Grupo,área (mm2),Grupo,área (mm2)
1,NaN,NaN,NaN,NaN,NaN,NaN,GD(+),C1,77.716,C1,...,NaN,NaN,NaN,OCC-TC,C1,67.335,C1,42.558,NaN,NaN
2,GD(+),82.019909,60.982333,36.4602,NaN,NaN,GD(+),C2,80.611,NaN,...,C2,33.558,NaN,OCC-TC,C2,137.562,NaN,NaN,C2,29.708
3,GS(-),70.579875,99.9,38.42,NaN,NaN,GD(+),C3,91.001,NaN,...,C3,59.947,NaN,OCC-TC,C3,94.324,NaN,NaN,C3,19.772
4,OCV,60.35675,57.88975,29.83225,NaN,NaN,GD(+),C4,98.15,C4,...,NaN,NaN,NaN,OCC-TC,C4,104.873,NaN,NaN,C4,37.599

['Tratamento', 'Dia zero', 'Dia 4', 'Dia 8', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'DIA ZERO', 'Unnamed: 8', 'Dia 4.1', 'Unnamed: 10', 'Dia 8.1', 'Unnamed: 12', 'Unnamed: 13', 'DIA ZERO.1', 'Unnamed: 15', 'Unnamed: 16', 'Dia 4.2', 'Unnamed: 18', 'Dia 8.2', 'Unnamed: 20']

In [10]:
print("df_x colunas:")
print(df_x.columns.tolist())

print("\ndf_y colunas:")
print(df_y.columns.tolist())

df_x colunas:
['Unnamed: 0', 'Composto', 'Teor (mg/mL)', 'Unnamed: 3', 'Unnamed: 4', 'Teor (mg/mL).1', 'Unnamed: 6', 'Unnamed: 7', 'Teor (mg/mL).2', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Teor (mg/mL).3', 'Unnamed: 15']

df_y colunas:
['Tratamento', 'Dia zero', 'Dia 4', 'Dia 8', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'DIA ZERO', 'Unnamed: 8', 'Dia 4.1', 'Unnamed: 10', 'Dia 8.1', 'Unnamed: 12', 'Unnamed: 13', 'DIA ZERO.1', 'Unnamed: 15', 'Unnamed: 16', 'Dia 4.2', 'Unnamed: 18', 'Dia 8.2', 'Unnamed: 20']

In [11]:
df_x.columns = df_x.columns.str.strip()
df_y.columns = df_y.columns.str.strip()

In [13]:
df = pd.merge(df_x, df_y, left_on=df_x.columns[0], right_on=df_y.columns[0])

In [15]:
import pandas as pd
import numpy as np

arquivo = "/content/Tabela analise multivariada_FJMN (2).xlsx"

df_x_raw = pd.read_excel(arquivo, sheet_name="Componentes dos óleos", header=None)
display(df_x_raw.head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Composto,Teor (mg/mL),NaN,NaN,Teor (mg/mL),NaN,NaN,Teor (mg/mL),NaN,NaN,NaN,NaN,NaN,Teor (mg/mL),NaN
1,tR (min),NaN,OCV,OCV-B,NaN,OCB,OCB-B,NaN,OCC,OCC-TC,OCC-TM,OCC-TE,OCC-TME,NaN,OC-BR,OC-BD
2,5.71,Ácido palmítico,1.811095,4.755756,NaN,1.939807,3.088236,NaN,0.504649,0.782495,1.895978,2.408786,3.676306,NaN,0.885206,0.711454
3,6.39,Cafeína,0.370544,1.009628,NaN,0.349252,0.564784,NaN,0.314963,0.360212,0.631691,0.553139,0.54365,NaN,0.359316,0.215336
4,6.47,Ácido linoleico,1.010604,1.706466,NaN,0.989264,1.003551,NaN,0.444661,0.85243,1.381854,1.249773,1.20735,NaN,1.584211,0.74008
5,8.13,Caveal,0.550683,0.513038,NaN,0.634226,0.560683,NaN,1.00562,1.209463,2.07564,2.008629,2.062697,NaN,0.555683,0.634226
6,8.22,"15,16-dehydro-caveol",0.826202,0.917395,NaN,1.214631,1.010749,NaN,0.739335,1.041805,4.272761,6.665273,8.719215,NaN,0.917395,1.31986
7,8.31,Cafestal,0.846768,0.567505,NaN,2.375339,1.297941,NaN,0.70547,0.366832,0.776834,0.545147,1.335977,NaN,2.822587,1.275307
8,8.46,"15,16-dehydro-cafestol",0.390452,0.551727,NaN,0.746493,1.605316,NaN,1.21374,1.079835,1.902998,4.979886,10.797935,NaN,0.51672,0.721195
9,8.51,Dehidro-caveol,0.702982,0.78961,NaN,1.448226,0.724275,NaN,1.5748,1.341463,1.897175,3.615129,8.075606,NaN,1.011376,0.964808

In [16]:
# linha 1 deve ter os códigos das amostras
amostras = df_x_raw.iloc[1, 2:].tolist()
print(amostras)

# dados começam na linha 2
df_x = df_x_raw.iloc[2:, 1:2+len(amostras)].copy()
df_x.columns = ["Composto"] + amostras
df_x = df_x.set_index("Composto")

# limpar números
df_x = df_x.replace("_", np.nan)
df_x = df_x.map(lambda x: str(x).replace(",", ".") if isinstance(x, str) else x)
df_x = df_x.apply(pd.to_numeric, errors="coerce")

display(df_x.head())
print(df_x.shape)

['OCV', 'OCV-B', np.float64(nan), 'OCB', 'OCB-B', np.float64(nan), 'OCC', 'OCC-TC', 'OCC-TM', 'OCC-TE', 'OCC-TME', np.float64(nan), 'OC-BR', 'OC-BD']

,OCV,OCV-B,NaN,OCB,OCB-B,NaN,OCC,OCC-TC,OCC-TM,OCC-TE,OCC-TME,NaN,OC-BR,OC-BD
Composto,,,,,,,,,,,,,,
Ácido palmítico,1.811095,4.755756,NaN,1.939807,3.088236,NaN,0.504649,0.782495,1.895978,2.408786,3.676306,NaN,0.885206,0.711454
Cafeína,0.370544,1.009628,NaN,0.349252,0.564784,NaN,0.314963,0.360212,0.631691,0.553139,0.543650,NaN,0.359316,0.215336
Ácido linoleico,1.010604,1.706466,NaN,0.989264,1.003551,NaN,0.444661,0.852430,1.381854,1.249773,1.207350,NaN,1.584211,0.740080
Caveal,0.550683,0.513038,NaN,0.634226,0.560683,NaN,1.005620,1.209463,2.075640,2.008629,2.062697,NaN,0.555683,0.634226
"15,16-dehydro-caveol",0.826202,0.917395,NaN,1.214631,1.010749,NaN,0.739335,1.041805,4.272761,6.665273,8.719215,NaN,0.917395,1.319860

(37, 14)

In [17]:
df_y_raw = pd.read_excel(arquivo, sheet_name="Cicatrização (área da ferida)", header=None)
display(df_y_raw.head(10))

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Tratamento,Dia zero,Dia 4,Dia 8,NaN,NaN,NaN,DIA ZERO,NaN,Dia 4,...,Dia 8,NaN,NaN,DIA ZERO,NaN,NaN,Dia 4,NaN,Dia 8,NaN
1,NaN,Área (Média),Área (Média),Área (Média),NaN,NaN,Tratamento,Grupo,Area (mm2),GRUPO,...,GRUPO,Area (mm2),NaN,Tratamento,Grupo,área (mm2),Grupo,área (mm2),Grupo,área (mm2)
2,NaN,NaN,NaN,NaN,NaN,NaN,GD(+),C1,77.716,C1,...,NaN,NaN,NaN,OCC-TC,C1,67.335,C1,42.558,NaN,NaN
3,GD(+),82.019909,60.982333,36.4602,NaN,NaN,GD(+),C2,80.611,NaN,...,C2,33.558,NaN,OCC-TC,C2,137.562,NaN,NaN,C2,29.708
4,GS(-),70.579875,99.9,38.42,NaN,NaN,GD(+),C3,91.001,NaN,...,C3,59.947,NaN,OCC-TC,C3,94.324,NaN,NaN,C3,19.772
5,OCV,60.35675,57.88975,29.83225,NaN,NaN,GD(+),C4,98.15,C4,...,NaN,NaN,NaN,OCC-TC,C4,104.873,NaN,NaN,C4,37.599
6,OCC,98.598947,71.5095,28.094,NaN,NaN,GD(+),C5,51.5,C5,...,NaN,NaN,NaN,OCC-TC,C5,83.676,NaN,NaN,C5,21.096
7,OCB,89.933615,69.024,40.840667,NaN,NaN,GD(+),C6,78.873,NaN,...,C6,21.012,NaN,OCC-TC,C6,65.488,NaN,NaN,C6,25.189
8,OCV-B,87.689643,76.096857,15.479143,NaN,NaN,GD(+),C7,56.322,C7,...,NaN,NaN,NaN,OCC-TC,C7,69.245,C7,45.886,NaN,NaN
9,OCB-B,71.311571,62.8655,29.608167,NaN,NaN,GD(+),C8,73.444,C8,...,NaN,NaN,NaN,OCC-TC,C8,63.268,C8,44.838,NaN,NaN

In [18]:
# ver a estrutura real
for i in range(10):
    print(i, df_y_raw.iloc[i].tolist())

0 ['Tratamento', 'Dia zero', 'Dia 4', 'Dia 8', np.float64(nan), np.float64(nan), nan, 'DIA ZERO', nan, 'Dia 4', nan, 'Dia 8', nan, np.float64(nan), 'DIA ZERO', nan, nan, 'Dia 4', nan, 'Dia 8', nan]
1 [nan, 'Área (Média)', 'Área (Média)', 'Área (Média)', np.float64(nan), np.float64(nan), 'Tratamento', 'Grupo', 'Area (mm2)', 'GRUPO', 'Area (mm2)', 'GRUPO', 'Area (mm2)', np.float64(nan), 'Tratamento', 'Grupo', 'área (mm2)', 'Grupo', 'área (mm2)', 'Grupo', 'área (mm2)']
2 [nan, nan, nan, nan, np.float64(nan), np.float64(nan), 'GD(+)', 'C1', 77.716, 'C1', 54.012, nan, nan, np.float64(nan), 'OCC-TC', 'C1', 67.335, 'C1', 42.558, nan, nan]
3 ['GD(+)', 82.01990909090908, 60.98233333333334, 36.4602, np.float64(nan), np.float64(nan), 'GD(+)', 'C2', 80.611, nan, nan, 'C2', 33.558, np.float64(nan), 'OCC-TC', 'C2', 137.562, nan, nan, 'C2', 29.708]
4 ['GS(-)', 70.579875, 99.9, 38.42, np.float64(nan), np.float64(nan), 'GD(+)', 'C3', 91.001, nan, nan, 'C3', 59.947, np.float64(nan), 'OCC-TC', 'C3', 94.324, nan, nan, 'C3', 19.772]
5 ['OCV', 60.35675, 57.88975, 29.832249999999995, np.float64(nan), np.float64(nan), 'GD(+)', 'C4', 98.15, 'C4', 78.215, nan, nan, np.float64(nan), 'OCC-TC', 'C4', 104.873, nan, nan, 'C4', 37.599]
6 ['OCC', 98.5989473684211, 71.5095, 28.094, np.float64(nan), np.float64(nan), 'GD(+)', 'C5', 51.5, 'C5', 68.504, nan, nan, np.float64(nan), 'OCC-TC', 'C5', 83.676, nan, nan, 'C5', 21.096]
7 ['OCB', 89.93361538461538, 69.024, 40.840666666666664, np.float64(nan), np.float64(nan), 'GD(+)', 'C6', 78.873, nan, nan, 'C6', 21.012, np.float64(nan), 'OCC-TC', 'C6', 65.488, nan, nan, 'C6', 25.189]
8 ['OCV-B', 87.6896428571429, 76.09685714285715, 15.479142857142858, np.float64(nan), np.float64(nan), 'GD(+)', 'C7', 56.322, 'C7', 51.774, nan, nan, np.float64(nan), 'OCC-TC', 'C7', 69.245, 'C7', 45.886, nan, nan]
9 ['OCB-B', 71.3115714285714, 62.8655, 29.608166666666666, np.float64(nan), np.float64(nan), 'GD(+)', 'C8', 73.444, 'C8', 54.956, nan, nan, np.float64(nan), 'OCC-TC', 'C8', 63.268, 'C8', 44.838, nan, nan]

In [19]:
df_y = df_y_raw.iloc[1:, :4].copy()
df_y.columns = ["Tratamento", "Dia_zero", "Dia_4", "Dia_8"]
df_y = df_y.dropna(subset=["Tratamento"])
display(df_y.head(10))
print(df_y.shape)

   Tratamento   Dia_zero      Dia_4      Dia_8
3       GD(+)  82.019909  60.982333    36.4602
4       GS(-)  70.579875       99.9      38.42
5         OCV   60.35675   57.88975   29.83225
6         OCC  98.598947    71.5095     28.094
7         OCB  89.933615     69.024  40.840667
8       OCV-B  87.689643  76.096857  15.479143
9       OCB-B  71.311571    62.8655  29.608167
10      OC-BD  77.936167     59.534  33.247125
11      OC-BR  89.543333      63.32  10.496333
12     OCC-TC  87.536333    54.6084  32.278571

(13, 4)

In [20]:
mapa = {
    "Óleo de grão cru cereja": "OCC",
    "Óleo de grão cru boia": "OCB",
    "Óleo de grão cru verde": "OCV",
}
df_y["Código"] = df_y["Tratamento"].map(mapa)

In [21]:
display(df_x_raw.head(10))
display(df_y_raw.head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Composto,Teor (mg/mL),NaN,NaN,Teor (mg/mL),NaN,NaN,Teor (mg/mL),NaN,NaN,NaN,NaN,NaN,Teor (mg/mL),NaN
1,tR (min),NaN,OCV,OCV-B,NaN,OCB,OCB-B,NaN,OCC,OCC-TC,OCC-TM,OCC-TE,OCC-TME,NaN,OC-BR,OC-BD
2,5.71,Ácido palmítico,1.811095,4.755756,NaN,1.939807,3.088236,NaN,0.504649,0.782495,1.895978,2.408786,3.676306,NaN,0.885206,0.711454
3,6.39,Cafeína,0.370544,1.009628,NaN,0.349252,0.564784,NaN,0.314963,0.360212,0.631691,0.553139,0.54365,NaN,0.359316,0.215336
4,6.47,Ácido linoleico,1.010604,1.706466,NaN,0.989264,1.003551,NaN,0.444661,0.85243,1.381854,1.249773,1.20735,NaN,1.584211,0.74008
5,8.13,Caveal,0.550683,0.513038,NaN,0.634226,0.560683,NaN,1.00562,1.209463,2.07564,2.008629,2.062697,NaN,0.555683,0.634226
6,8.22,"15,16-dehydro-caveol",0.826202,0.917395,NaN,1.214631,1.010749,NaN,0.739335,1.041805,4.272761,6.665273,8.719215,NaN,0.917395,1.31986
7,8.31,Cafestal,0.846768,0.567505,NaN,2.375339,1.297941,NaN,0.70547,0.366832,0.776834,0.545147,1.335977,NaN,2.822587,1.275307
8,8.46,"15,16-dehydro-cafestol",0.390452,0.551727,NaN,0.746493,1.605316,NaN,1.21374,1.079835,1.902998,4.979886,10.797935,NaN,0.51672,0.721195
9,8.51,Dehidro-caveol,0.702982,0.78961,NaN,1.448226,0.724275,NaN,1.5748,1.341463,1.897175,3.615129,8.075606,NaN,1.011376,0.964808

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Tratamento,Dia zero,Dia 4,Dia 8,NaN,NaN,NaN,DIA ZERO,NaN,Dia 4,...,Dia 8,NaN,NaN,DIA ZERO,NaN,NaN,Dia 4,NaN,Dia 8,NaN
1,NaN,Área (Média),Área (Média),Área (Média),NaN,NaN,Tratamento,Grupo,Area (mm2),GRUPO,...,GRUPO,Area (mm2),NaN,Tratamento,Grupo,área (mm2),Grupo,área (mm2),Grupo,área (mm2)
2,NaN,NaN,NaN,NaN,NaN,NaN,GD(+),C1,77.716,C1,...,NaN,NaN,NaN,OCC-TC,C1,67.335,C1,42.558,NaN,NaN
3,GD(+),82.019909,60.982333,36.4602,NaN,NaN,GD(+),C2,80.611,NaN,...,C2,33.558,NaN,OCC-TC,C2,137.562,NaN,NaN,C2,29.708
4,GS(-),70.579875,99.9,38.42,NaN,NaN,GD(+),C3,91.001,NaN,...,C3,59.947,NaN,OCC-TC,C3,94.324,NaN,NaN,C3,19.772
5,OCV,60.35675,57.88975,29.83225,NaN,NaN,GD(+),C4,98.15,C4,...,NaN,NaN,NaN,OCC-TC,C4,104.873,NaN,NaN,C4,37.599
6,OCC,98.598947,71.5095,28.094,NaN,NaN,GD(+),C5,51.5,C5,...,NaN,NaN,NaN,OCC-TC,C5,83.676,NaN,NaN,C5,21.096
7,OCB,89.933615,69.024,40.840667,NaN,NaN,GD(+),C6,78.873,NaN,...,C6,21.012,NaN,OCC-TC,C6,65.488,NaN,NaN,C6,25.189
8,OCV-B,87.689643,76.096857,15.479143,NaN,NaN,GD(+),C7,56.322,C7,...,NaN,NaN,NaN,OCC-TC,C7,69.245,C7,45.886,NaN,NaN
9,OCB-B,71.311571,62.8655,29.608167,NaN,NaN,GD(+),C8,73.444,C8,...,NaN,NaN,NaN,OCC-TC,C8,63.268,C8,44.838,NaN,NaN

In [22]:
import pandas as pd, numpy as np; arquivo='/content/Tabela analise multivariada_FJMN (2).xlsx'; x_raw=pd.read_excel(arquivo,sheet_name='Componentes dos óleos',header=None); amostras=[v for v in x_raw.iloc[1,2:].tolist() if pd.notna(v)]; cols=[i for i,v in enumerate(x_raw.iloc[1,2:].tolist(),start=2) if pd.notna(v)]; x=x_raw.iloc[2:,[1]+cols].copy(); x.columns=['Composto']+amostras; x=x.set_index('Composto').apply(pd.to_numeric,errors='coerce').T.reset_index().rename(columns={'index':'Código'}); y_raw=pd.read_excel(arquivo,sheet_name='Cicatrização (área da ferida)',header=None); y=y_raw.iloc[3:,0:4].copy(); y.columns=['Código','Dia_zero','Dia_4','Dia_8']; y=y.dropna(subset=['Código']); y[['Dia_zero','Dia_4','Dia_8']]=y[['Dia_zero','Dia_4','Dia_8']].apply(pd.to_numeric,errors='coerce'); df=pd.merge(x,y,on='Código',how='inner'); print(df.shape); display(df.head())

(11, 41)

,Código,Ácido palmítico,Cafeína,Ácido linoleico,Caveal,"15,16-dehydro-caveol",Cafestal,"15,16-dehydro-cafestol",Dehidro-caveol,Dehidro-caveol derivado,...,1-palmitoil-2-oleoil-3-linoleoil-glicerol (POL),"1-palmitoil-2,3-dilinoleoil-glicerol (PLL)",1-palmitoil-2-linoleoil-3-araquidonil-glicerol (PLA),1-estearoil-2-oleoil-3-linoleoil-glicerol (SOL),1-estearoil-2-linoleoil-3-linolenoil-glicerol (SLLn),1-oleoil-2-linoleoil-3-linolenoil-glicerol (OLLn),"1,2-dilinoleoil-3-linolenoil-glicerol (LLLn)",Dia_zero,Dia_4,Dia_8
0,OCV,1.811095,0.370544,1.010604,0.550683,0.826202,0.846768,0.390452,0.702982,0.787559,...,2.008116,11.604823,0.376629,0.219093,1.199233,1.353753,1.614579,60.356750,57.889750,29.832250
1,OCV-B,4.755756,1.009628,1.706466,0.513038,0.917395,0.567505,0.551727,0.789610,0.544502,...,13.205319,49.992889,1.410673,1.654879,4.346459,4.043639,5.001916,87.689643,76.096857,15.479143
2,OCB,1.939807,0.349252,0.989264,0.634226,1.214631,2.375339,0.746493,1.448226,0.776962,...,0.007111,9.409003,0.378009,0.278829,0.789033,0.624733,0.841499,89.933615,69.024000,40.840667
3,OCB-B,3.088236,0.564784,1.003551,0.560683,1.010749,1.297941,1.605316,0.724275,0.535875,...,1.579726,13.313113,0.428706,0.194366,0.915909,1.227733,0.007111,71.311571,62.865500,29.608167
4,OCC,0.504649,0.314963,0.444661,1.005620,0.739335,0.705470,1.213740,1.574800,0.628767,...,0.007111,10.749509,0.527983,0.424976,1.292596,1.254923,1.632056,98.598947,71.509500,28.094000

In [23]:
import pandas as pd
import numpy as np

# ===== arquivo =====
arquivo = "/content/Tabela analise multivariada_FJMN (2).xlsx"

# =========================================================
# 1) TABELA QUÍMICA: componentes dos óleos
# =========================================================
x_raw = pd.read_excel(arquivo, sheet_name="Componentes dos óleos", header=None)

# nomes das amostras estão na linha 1, mas há colunas vazias entre elas
linha_amostras = x_raw.iloc[1, 2:].tolist()
amostras = [v for v in linha_amostras if pd.notna(v)]
cols_validas = [i for i, v in enumerate(linha_amostras, start=2) if pd.notna(v)]

# monta tabela: 1 coluna de composto + colunas das amostras
x = x_raw.iloc[2:, [1] + cols_validas].copy()
x.columns = ["Composto"] + amostras

# converte para formato amostra x composto
x = x.set_index("Composto")
x = x.apply(pd.to_numeric, errors="coerce")
x = x.T.reset_index().rename(columns={"index": "Código"})

print("Tabela química:")
print(x.shape)
display(x.head())

# =========================================================
# 2) TABELA BIOLÓGICA: cicatrização (área da ferida) - médias
# =========================================================
y_raw = pd.read_excel(arquivo, sheet_name="Cicatrização (área da ferida)", header=None)

# tabela de médias está na parte esquerda
y = y_raw.iloc[3:, 0:4].copy()
y.columns = ["Código", "Dia_zero", "Dia_4", "Dia_8"]

# remove linhas vazias
y = y.dropna(subset=["Código"])

# converte valores para numérico
for c in ["Dia_zero", "Dia_4", "Dia_8"]:
    y[c] = pd.to_numeric(y[c], errors="coerce")

print("Tabela biológica:")
print(y.shape)
display(y.head())

# =========================================================
# 3) JUNÇÃO QUÍMICA + BIOLÓGICA
# =========================================================
df = pd.merge(x, y, on="Código", how="inner")

# cria variável de contração no dia 8
df["Contracao_D8"] = (df["Dia_zero"] - df["Dia_8"]) / df["Dia_zero"]

print("Tabela final unificada:")
print(df.shape)
display(df.head())

print("Colunas:")
print(df.columns.tolist())

Tabela química:
(11, 38)

Composto,Código,Ácido palmítico,Cafeína,Ácido linoleico,Caveal,"15,16-dehydro-caveol",Cafestal,"15,16-dehydro-cafestol",Dehidro-caveol,Dehidro-caveol derivado,...,"1,2-dipalmitoll-3-oleoll glicerol (PPO)","1,2-dipalmitoll-3-linoleoll glicerol (PPL)",1-palmitoil-2-stearoil-3-linoleoil-glicerol (PSL),1-palmitoil-2-oleoil-3-linoleoil-glicerol (POL),"1-palmitoil-2,3-dilinoleoil-glicerol (PLL)",1-palmitoil-2-linoleoil-3-araquidonil-glicerol (PLA),1-estearoil-2-oleoil-3-linoleoil-glicerol (SOL),1-estearoil-2-linoleoil-3-linolenoil-glicerol (SLLn),1-oleoil-2-linoleoil-3-linolenoil-glicerol (OLLn),"1,2-dilinoleoil-3-linolenoil-glicerol (LLLn)"
0,OCV,1.811095,0.370544,1.010604,0.550683,0.826202,0.846768,0.390452,0.702982,0.787559,...,0.954826,10.684076,0.776943,2.008116,11.604823,0.376629,0.219093,1.199233,1.353753,1.614579
1,OCV-B,4.755756,1.009628,1.706466,0.513038,0.917395,0.567505,0.551727,0.789610,0.544502,...,0.963446,36.659556,0.007111,13.205319,49.992889,1.410673,1.654879,4.346459,4.043639,5.001916
2,OCB,1.939807,0.349252,0.989264,0.634226,1.214631,2.375339,0.746493,1.448226,0.776962,...,0.391749,11.175296,0.781499,0.007111,9.409003,0.378009,0.278829,0.789033,0.624733,0.841499
3,OCB-B,3.088236,0.564784,1.003551,0.560683,1.010749,1.297941,1.605316,0.724275,0.535875,...,0.583713,14.918126,0.433673,1.579726,13.313113,0.428706,0.194366,0.915909,1.227733,0.007111
4,OCC,0.504649,0.314963,0.444661,1.005620,0.739335,0.705470,1.213740,1.574800,0.628767,...,0.459143,16.181586,0.007111,0.007111,10.749509,0.527983,0.424976,1.292596,1.254923,1.632056

Tabela biológica:
(13, 4)

  Código   Dia_zero      Dia_4      Dia_8
3  GD(+)  82.019909  60.982333  36.460200
4  GS(-)  70.579875  99.900000  38.420000
5    OCV  60.356750  57.889750  29.832250
6    OCC  98.598947  71.509500  28.094000
7    OCB  89.933615  69.024000  40.840667

Tabela final unificada:
(11, 42)

,Código,Ácido palmítico,Cafeína,Ácido linoleico,Caveal,"15,16-dehydro-caveol",Cafestal,"15,16-dehydro-cafestol",Dehidro-caveol,Dehidro-caveol derivado,...,"1-palmitoil-2,3-dilinoleoil-glicerol (PLL)",1-palmitoil-2-linoleoil-3-araquidonil-glicerol (PLA),1-estearoil-2-oleoil-3-linoleoil-glicerol (SOL),1-estearoil-2-linoleoil-3-linolenoil-glicerol (SLLn),1-oleoil-2-linoleoil-3-linolenoil-glicerol (OLLn),"1,2-dilinoleoil-3-linolenoil-glicerol (LLLn)",Dia_zero,Dia_4,Dia_8,Contracao_D8
0,OCV,1.811095,0.370544,1.010604,0.550683,0.826202,0.846768,0.390452,0.702982,0.787559,...,11.604823,0.376629,0.219093,1.199233,1.353753,1.614579,60.356750,57.889750,29.832250,0.505735
1,OCV-B,4.755756,1.009628,1.706466,0.513038,0.917395,0.567505,0.551727,0.789610,0.544502,...,49.992889,1.410673,1.654879,4.346459,4.043639,5.001916,87.689643,76.096857,15.479143,0.823478
2,OCB,1.939807,0.349252,0.989264,0.634226,1.214631,2.375339,0.746493,1.448226,0.776962,...,9.409003,0.378009,0.278829,0.789033,0.624733,0.841499,89.933615,69.024000,40.840667,0.545880
3,OCB-B,3.088236,0.564784,1.003551,0.560683,1.010749,1.297941,1.605316,0.724275,0.535875,...,13.313113,0.428706,0.194366,0.915909,1.227733,0.007111,71.311571,62.865500,29.608167,0.584806
4,OCC,0.504649,0.314963,0.444661,1.005620,0.739335,0.705470,1.213740,1.574800,0.628767,...,10.749509,0.527983,0.424976,1.292596,1.254923,1.632056,98.598947,71.509500,28.094000,0.715068

Colunas:
['Código', 'Ácido palmítico', 'Cafeína', 'Ácido linoleico', 'Caveal', '15,16-dehydro-caveol', 'Cafestal', '15,16-dehydro-cafestol', 'Dehidro-caveol', 'Dehidro-caveol derivado', 'Dehidro-cafestol', 'Caveol', 'Cafestol', 'Tocoferol', 'Campesterol', 'Estigmasterol', 'β-sitosterol', 'Palmitato de caveol', 'Palmitato de cafestol', 'Estearato de caveol', 'Oleato de caveol', 'Estearato de cafestol', 'Linoleato de caveol', 'Oleato de cafestol', 'Linoleato de cafestol', 'Araquidato de caveol', 'Araquidato de cafestol', '1,2,3-tripalmitoil-glicerol (PPP)', '1,2-dipalmitoll-3-oleoll glicerol (PPO)', '1,2-dipalmitoll-3-linoleoll glicerol (PPL)', '1-palmitoil-2-stearoil-3-linoleoil-glicerol (PSL)', '1-palmitoil-2-oleoil-3-linoleoil-glicerol (POL)', '1-palmitoil-2,3-dilinoleoil-glicerol (PLL)', '1-palmitoil-2-linoleoil-3-araquidonil-glicerol (PLA)', '1-estearoil-2-oleoil-3-linoleoil-glicerol (SOL)', '1-estearoil-2-linoleoil-3-linolenoil-glicerol (SLLn)', '1-oleoil-2-linoleoil-3-linolenoil-glicerol (OLLn)', '1,2-dilinoleoil-3-linolenoil-glicerol (LLLn)', 'Dia_zero', 'Dia_4', 'Dia_8', 'Contracao_D8']

In [24]:
df.shape

(11, 42)

In [26]:
df.head()

,Código,Ácido palmítico,Cafeína,Ácido linoleico,Caveal,"15,16-dehydro-caveol",Cafestal,"15,16-dehydro-cafestol",Dehidro-caveol,Dehidro-caveol derivado,...,"1-palmitoil-2,3-dilinoleoil-glicerol (PLL)",1-palmitoil-2-linoleoil-3-araquidonil-glicerol (PLA),1-estearoil-2-oleoil-3-linoleoil-glicerol (SOL),1-estearoil-2-linoleoil-3-linolenoil-glicerol (SLLn),1-oleoil-2-linoleoil-3-linolenoil-glicerol (OLLn),"1,2-dilinoleoil-3-linolenoil-glicerol (LLLn)",Dia_zero,Dia_4,Dia_8,Contracao_D8
0,OCV,1.811095,0.370544,1.010604,0.550683,0.826202,0.846768,0.390452,0.702982,0.787559,...,11.604823,0.376629,0.219093,1.199233,1.353753,1.614579,60.356750,57.889750,29.832250,0.505735
1,OCV-B,4.755756,1.009628,1.706466,0.513038,0.917395,0.567505,0.551727,0.789610,0.544502,...,49.992889,1.410673,1.654879,4.346459,4.043639,5.001916,87.689643,76.096857,15.479143,0.823478
2,OCB,1.939807,0.349252,0.989264,0.634226,1.214631,2.375339,0.746493,1.448226,0.776962,...,9.409003,0.378009,0.278829,0.789033,0.624733,0.841499,89.933615,69.024000,40.840667,0.545880
3,OCB-B,3.088236,0.564784,1.003551,0.560683,1.010749,1.297941,1.605316,0.724275,0.535875,...,13.313113,0.428706,0.194366,0.915909,1.227733,0.007111,71.311571,62.865500,29.608167,0.584806
4,OCC,0.504649,0.314963,0.444661,1.005620,0.739335,0.705470,1.213740,1.574800,0.628767,...,10.749509,0.527983,0.424976,1.292596,1.254923,1.632056,98.598947,71.509500,28.094000,0.715068

In [28]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# ==============================
# 1) definir X e y
# ==============================

y = df["Contracao_D8"]

cols_meta = ["Código","Dia_zero","Dia_4","Dia_8","Contracao_D8"]
X = df.drop(columns=cols_meta)

# ==============================
# 2) padronizar
# ==============================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ==============================
# 3) modelo PLS
# ==============================

pls = PLSRegression(n_components=3)

loo = LeaveOneOut()

y_real = []
y_pred = []

for train, test in loo.split(X_scaled):

    X_train, X_test = X_scaled[train], X_scaled[test]
    y_train, y_test = y.iloc[train], y.iloc[test]

    pls.fit(X_train, y_train)

    pred = pls.predict(X_test)

    y_real.append(float(y_test))
    y_pred.append(float(pred))

# ==============================
# 4) métricas
# ==============================

r2 = r2_score(y_real, y_pred)
rmse = np.sqrt(mean_squared_error(y_real, y_pred))

print("R2:", r2)
print("RMSE:", rmse)

resultado = pd.DataFrame({
    "real": y_real,
    "predito": y_pred
})

display(resultado)

R2: 0.26664957910650267
RMSE: 0.09663845777328972

/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))
/tmp/ipykernel_258/3348342727.py:44: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  y_real.append(float(y_test))
/tmp/ipykernel_258/3348342727.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred.append(float(pred))

        real   predito
0   0.505735  0.605943
1   0.823478  0.909547
2   0.545880  0.581325
3   0.584806  0.588962
4   0.715068  0.543490
5   0.631255  0.655664
6   0.745605  0.784226
7   0.693547  0.626721
8   0.722291  0.661783
9   0.882779  0.673647
10  0.573406  0.598227